dist: xenial
sudo: required
language: c
env:
  global:
  - CONAN_PKG: conan-ubuntu-64_1_23_0.deb
cache:
  directories:
  - "$HOME/.conan/"
addons:
  apt:
    sources:
    - sourceline: deb https://apt.kitware.com/ubuntu/ xenial main
      key_url: https://apt.kitware.com/keys/kitware-archive-latest.asc
    packages:
    - cmake
    - p7zip-full
    - pkg-config
    - ninja-build
    - nvidia-cg-toolkit
    - libfreetype6-dev
    - libfreeimage-dev
    - libzzip-dev
    - libois-dev
    - libgl1-mesa-dev
    - libglu1-mesa-dev
    - libx11-dev
    - libxt-dev
    - libxaw7-dev
    - libxrandr-dev
install:
- wget https://dl.bintray.com/conan/installers/$CONAN_PKG -nv
- sudo dpkg -i ./$CONAN_PKG
- conan user
script:
- cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DBUILD_REDIST_FOLDER=ON -DBUILD_CUSTOM_VERSION=ON
  -DCUSTOM_VERSION="2020.01" -DBUILD_DEV_VERSION=OFF .
- ninja
before_cache:
- cmake -P ./cmake/3rdparty/pmm.cmake /Conan /Clean
after_success:
- sh ./tools/CI/upload-CI-build.sh

deploy:
  provider: releases
  api_key:
    secure: k7da9CxeSeBpMh3LxJftMTf2LH2wVUzp3Zn2jojwasPYcx8Xpj5wsh12kbBA1wTQ/GbMbhuwy28uxRN5rDdhSCWJYz94fl7jNsH4LFhvVY7ioaf/vbRIltlbD6e5SKEcqgqg4/FotA6zBoa3uGgox/DT2e45s6wIzUiO9bbViSxZXFKXsoASCy2d0yJ+yxH1feZ8xypNwKP94tJre+NU7O+ZjYRCuWxslM1eTR0x8kVBW81hbOVbsLzTx6Pid2kDoyDA9BZrO0G6dMTrrWoYyjyoRw2EQOPcoWIG4xPKEVBkmxdk8XMV5YF9NZwdtp9FWa6T4CWtJuPc5Vqgn2IB/mnEV5yp09mN5RWHnP44s4Z79plFEhtG9HhFQUmSig83VMPVLUvVNLJHqff1fFvJx6dOvbkgByOhIbv3NT66nLEXltGNaw6DW8Y4lMC0Js8OS0cmaA8N4Cg1NH161xnNVaTyhoT/59ulyafkHdzHlouoPxdVKz/SlryPkDHWKT23IurKJcK18IlG52ZW0tn3b0GdXe/Hxwl1oXkrgLb14j29uO1cy7XL3vhP7y3B3a7D5hKuJs0Y90d4wQDEkyWfNZKc5pPHm/OPxX+VWrf8JuAzwouGN6/xe0y1ra9B/oQVebx1ns9ndE/6vQRznvjvMhsHHqUlkazvpzOfCkYGORY=
  file: ror-release.7z
  on:
    repo: AnotherFoxGuy/rigs-of-rods
    branch: release
