name: Build flatpak
on:
  push:
    branches: [master, flatpak]
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-25.08
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: Rigs-of-Rods.flatpak
          manifest-path: org.rigsofrods.RigsOfRods.yml

      - name: Upload Flatpak artifact
        uses: actions/upload-artifact@v7
        with:
          name: Rigs-of-Rods-flatpak
          path: "Rigs-of-Rods.flatpak"
          retention-days: 30