---
name: Build game

on: [ push, pull_request ]

jobs:
  build-gcc:
    name: Linux build on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Cache conan
        uses: actions/cache@v3
        with:
          key: conan-ubuntu-${{ hashFiles('cmake/DependenciesConfig.cmake') }}
          path: ~/.conan/

      - name: Install dependencies
        run: |
          curl "https://raw.githubusercontent.com/AnotherFoxGuy/ci-scripts/main/install-conan.sh" | sudo bash
          sudo apt-get update
          sudo apt-get -y install \
                  pkg-config \
                  ninja-build \
                  nvidia-cg-toolkit \
                  libfreetype6-dev \
                  libfreeimage-dev \
                  libzzip-dev \
                  libois-dev \
                  libgl1-mesa-dev \
                  libglu1-mesa-dev \
                  libx11-dev \
                  libx11-xcb-dev \
                  libfontenc-dev \
                  libice-dev \
                  libsm-dev \
                  libxau-dev \
                  libxaw7-dev \
                  libxcomposite-dev \
                  libxcursor-dev \
                  libxdamage-dev \
                  libxdmcp-dev \
                  libxext-dev \
                  libxfixes-dev \
                  libxi-dev \
                  libxinerama-dev \
                  libxkbfile-dev \
                  libxmu-dev \
                  libxmuu-dev \
                  libxpm-dev \
                  libxrandr-dev \
                  libxrender-dev \
                  libxres-dev \
                  libxss-dev \
                  libxt-dev \
                  libxtst-dev \
                  libxv-dev \
                  libxvmc-dev \
                  libxxf86vm-dev \
                  libxcb-render0-dev \
                  libxcb-render-util0-dev \
                  libxcb-xkb-dev \
                  libxcb-icccm4-dev \
                  libxcb-image0-dev \
                  libxcb-keysyms1-dev \
                  libxcb-randr0-dev \
                  libxcb-shape0-dev \
                  libxcb-sync-dev \
                  libxcb-xfixes0-dev \
                  libxcb-xinerama0-dev \
                  libxcb-dri3-dev \
                  libxcb-util-dev \
                  uuid-dev \
                  libxt-dev \
                  libxaw7-dev \
                  libxrandr-dev \
                  libopenjp2-7-dev

        shell: bash

      - name: Configure
        run: |
          conan config set general.revisions_enabled=1
          echo "tools.system.package_manager:mode = install" > ~/.conan/global.conf
          echo "tools.system.package_manager:sudo = True" >> ~/.conan/global.conf
          cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=redist -DCREATE_CONTENT_FOLDER=ON .
        shell: bash

      - name: Build
        run: ninja install
        shell: bash

      - name: Copy *.so files
        run: cmake -P ./tools/CI/copy_libs.cmake
        shell: bash

      - name: Upload build to itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        if: env.BUTLER_API_KEY != null && github.ref == 'refs/heads/master'
        run: |
          curl "https://raw.githubusercontent.com/AnotherFoxGuy/ci-scripts/main/install-butler.sh" | sudo bash
          butler push redist rigs-of-rods/rigs-of-rods-dev:linux-ci --userversion CIBuild-${GITHUB_RUN_NUMBER}-commit-${GITHUB_SHA}
        shell: bash

      - name: Upload redist folder
        uses: actions/upload-artifact@v3
        with:
          name: ror-linux
          path: redist

      - name: Clean Conan pkgs
        run: conan remove "*" -fsb
        shell: bash

  build-msvc:
    name: Windows build
    runs-on: windows-2019
    env:
      BUILD_TOOLS_PATH: C:\apps\build-tools\
      CONAN_USER_HOME_SHORT: None
    steps:
      - run: echo $env:BUILD_TOOLS_PATH | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Build tools
        shell: cmake -P {0}
        run: |
          file(MAKE_DIRECTORY $ENV{BUILD_TOOLS_PATH})
          file(DOWNLOAD https://cdn.anotherfoxguy.com/build-tools.zip "$ENV{TMP}/build-tools.zip" SHOW_PROGRESS)
          execute_process(COMMAND ${CMAKE_COMMAND} -E tar xzf "$ENV{TMP}/build-tools.zip" WORKING_DIRECTORY "$ENV{BUILD_TOOLS_PATH}")

      - name: Cache conan packages
        uses: actions/cache@v3
        with:
          key: conan-windows-${{ hashFiles('cmake/DependenciesConfig.cmake') }}
          path: ~/.conan

      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1.12.0

      - name: Configure
        run: |
          conan config set general.revisions_enabled=1
          cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=redist -DCREATE_CONTENT_FOLDER=ON .
        shell: cmd

      - name: Build
        run: ninja install
        shell: cmd

      - name: Upload build to itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        if: env.BUTLER_API_KEY != null && github.ref == 'refs/heads/master'
        run: |
          choco install butler -y
          butler push redist rigs-of-rods/rigs-of-rods-dev:windows-ci --userversion CIBuild-%GITHUB_RUN_NUMBER%-Commit-%GITHUB_SHA%
        shell: cmd

      - name: Upload redist folder
        uses: actions/upload-artifact@v3
        with:
          name: ror-win
          path: redist

      - name: Clean Conan pkgs
        run: conan remove "*" -fsb
        shell: cmd
