---
name: Build game with ror-deps

on: [push, pull_request]

jobs:
  build-msvc:
    name: Windows build
    runs-on: windows-2019
    env:
      BUILD_TOOLS_PATH: C:\apps\build-tools\
      CONAN_USER_HOME_SHORT: None
      SCCACHE_BUCKET: sccache
      SCCACHE_ENDPOINT: ${{ secrets.SCCACHE_ENDPOINT }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - run: echo $env:BUILD_TOOLS_PATH | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Build tools
        run: |
          choco install ninja wget sccache -y
          wget -nv https://minio.anotherfoxguy.com/filedump/Dependencies_Windows.zip
          7z x Dependencies_Windows.zip -Odependencies
        shell: cmd

      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1.12.0

      - name: Configure
        run: cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DCREATE_CONTENT_FOLDER=ON -DCMAKE_C_COMPILER_LAUNCHER=sccache -DCMAKE_CXX_COMPILER_LAUNCHER=sccache .
        shell: cmd

      - name: Build
        run: ninja
        shell: cmd