name: SonarCloud scan
on:
  push:
    branches:
      - master
      - sonarcloud
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: sonarcloud scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install sonar-scanner and build-wrapper
        uses: sonarsource/sonarcloud-github-c-cpp@v2
        id: sonarscan
        
      - name: Cache conan
        uses: actions/cache@v4
        with:
          key: conan-ubuntu-${{ hashFiles('conanfile.py') }}
          path: ~/.conan2/

      - name: Install dependencies
        run: |
          curl "https://raw.githubusercontent.com/AnotherFoxGuy/ci-scripts/main/install-conan.sh" | sudo bash
          sudo apt-get update
          wget -nv https://cdn.anotherfoxguy.com/sonar-scanner/ror -O run-sonar-scanner
          sudo chmod 777 run-sonar-scanner

      - name: Configure
        run: |
          conan profile detect --force
          echo "tools.system.package_manager:mode = install" > ~/.conan2/global.conf
          echo "tools.system.package_manager:sudo = True" >> ~/.conan2/global.conf
          conan remote add ror-conan https://git.anotherfoxguy.com/api/packages/rorbot/conan -f
          cmake . -DCMAKE_BUILD_TYPE=Release -DCMAKE_PROJECT_TOP_LEVEL_INCLUDES=cmake/conan_provider.cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
        shell: bash

      - name: Run sonar-scanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_SCANNER_EXE: ${{ steps.sonarscan.outputs.sonar-scanner-binary }}
        run: ./run-sonar-scanner

      - name: Clean Conan pkgs
        run: conan cache clean "*" -sbd